hostname: workflow-api.local
ingressClass: nginx
repo: datanosecr.azurecr.io
apiTag: latest
webTag: latest
certificateName: datanose-nl
environment: Test
contentSecurityPolicy: "default-src 'self'"
logLevel: Debug

allowedOrigins: "http://localhost:5173"

datanoseApi:
  baseAddress: https://api-v2-tst.datanose.nl/

graph:
  tenantId: tenantId
  clientId: clientId
  userAccount: datanose@amsuni.onmicrosoft.com
  overrideRecipient: testen-dn-fnwi@uva.nl
  
surfConext:
  baseUrl: https://connect.test.surfconext.nl
  clientId: datanose-api.local
  authority: https://auth-pr.datanose.nl

mongo:
  username: username
  database: workflow
  host: host
  port: 27017

apiPaths:
  - /swagger
  - /Actions
  - /Answers
  - /Screens
  - /Versions
  - /Submissions
  - /WorkflowDefinitions
  - /Users
  - /WorkflowInstances
  - /Submissions
  - /Artifacts

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: workflow-db-password
      key: Mongo__Password
    - name: dn2-api-key
      key: DatanoseApi__ApiKey
    - name: workflow-encryption-secret
      key: Encryption__Secret
    - name: workflow-surfconext-client-secret
      key: SurfConext__ClientSecret
    - name: workflow-impersonation-key
      key: ImpersonationKey
