apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-api-config
  namespace: "{{ .Release.Namespace }}"
data:
  DOTNET_ENVIRONMENT: "{{ .Values.environment }}"

  DataNoseApi__BaseAddress: "{{ .Values.datanoseApi.baseAddress }}"
 
  Serilog__MinimumLevel__Override__Uva.DataNose: "{{ .Values.logLevel }}"

  AllowedOrigins: "{{ .Values.allowedOrigins }}"
  
  SurfConext__BaseUrl: "{{ .Values.surfConext.baseUrl }}"
  SurfConext__ClientId: "{{ .Values.surfConext.clientId }}"
    
  Mongo__Username: "{{ .Values.mongo.username }}"
  Mongo__Database: "{{ .Values.mongo.database }}"
  Mongo__Host: "{{ .Values.mongo.host }}"
  Mongo__Port: "{{ .Values.mongo.port }}"