apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-ui
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: workflow-ui
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: workflow-ui
    spec:
      containers:
        - name: workflow-ui
          image: "{{ .Values.repo }}/workflow-ui:{{ .Values.webTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WORKFLOW_VERSION
              value: "{{ .Chart.AppVersion }}"
          volumeMounts:
            - name: env-file
              mountPath: /usr/share/nginx/html/environment.js
              subPath: env-contents
              readOnly: true
      volumes:
        - name: env-file
          configMap:
            name: workflow-ui-configmap