apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workflow-api-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Strict-Transport-Security: 'max-age=31536000; includeSubDomains' always"; # HSTS
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          {{- range .Values.apiPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: workflow-api
                port:
                  number: 80
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workflow-ui
                port:
                  number: 80
