hostname: workflow-api.local
ingressClass: nginx
repo: datanosecr.azurecr.io
tag: latest
certificateName: datanose-nl
environment: Test
contentSecurityPolicy: "default-src 'self'"
logLevel: Debug

allowedOrigins: "http://localhost:5173"

datanoseApi:
  baseAddress: https://api-v2-tst.datanose.nl/
  
surfConext:
  baseUrl: https://connect.test.surfconext.nl
  clientId: datanose-api.local

mongo:
  username: username
  database: workflow
  host: host
  port: 27017

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: workflow-db-password
      key: Mongo__Password
    - name: dn2-api-key
      key: DataNoseApi__ApiKey
    - name: workflow-surfconext-client-secret
      key: SurfConext__ClientSecret
    - name: workflow-impersonation-key
      key: ImpersonationKey
