hostname: workflow-api.local
ingressClass: nginx
repo: datanosecr.azurecr.io
tag: latest
certificateName: datanose-nl
environment: Test
contentSecurityPolicy: "default-src 'self'"
logLevel: Debug

allowedOrigins: "http://localhost:5173"

surfconext:
  baseUrl: https://connect.test.surfconext.nl
  clientId: v2-tst.datanose.nl

mongo:
  username: username
  database: workflow
  host: host
  port: 27017

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: workflow-db-password
      key: Mongo__Password
    - name: workflow-surfconext-client-secret
      key: SurfConext__ClientSecret